// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvinxafpklakttqdaydt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2aW54YWZwa2xha3R0cWRheWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjQ4NTIsImV4cCI6MjA3MTMwMDg1Mn0.Lil210LmZkwQnlYRONF5_OhRTJLv3kqngo_afl79_Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});